# Generated by Django 3.2.7 on 2021-12-02 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IMS_06_Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('Other', 'Other'), ('SHE', 'SHE'), ('HR', 'HR'), ('Finance', 'Finance'), ('Technical Services', 'Technical Services'), ('Reduction', 'Reduction'), ('Engineering', 'Engineering'), ('Security', 'Security'), ('Muriel Mine', 'Muriel Mine')], max_length=250)),
                ('category', models.CharField(choices=[('Other', 'Other'), ('Baseline Risk Assessment (BRA)', 'Baseline Risk Assessment (BRA)'), ('Issue Based Risk Assessment', 'Issue Based Risk Assessment'), ('Compliance Obligations Register', 'Compliance Obligations Register'), ('IMS Objectives and targets', 'IMS Objectives and targets'), ('ACTs', 'ACTs'), ('Blank forms', 'Blank forms')], max_length=250)),
                ('description', models.TextField(blank=True)),
                ('name', models.CharField(blank=True, max_length=250)),
                ('upload_file', models.FileField(upload_to='ims_06')),
                ('active', models.BooleanField(default=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
        migrations.CreateModel(
            name='BlankForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('Other', 'Other'), ('SHE', 'SHE'), ('HR', 'HR'), ('Finance', 'Finance'), ('Technical Services', 'Technical Services'), ('Reduction', 'Reduction'), ('Engineering', 'Engineering'), ('Security', 'Security'), ('Muriel Mine', 'Muriel Mine')], max_length=250)),
                ('name', models.CharField(choices=[('Appointmant form', 'Appointmant form'), ('Accident form', 'Accident form'), ('CAPEX form', 'CAPEX form'), ('Clinic Form', 'Clinic Form'), ('Charge form', 'Charge form'), ('Canteen meals booking', 'Canteen meals booking'), ('Change request form', 'Change request form'), ('EMA form', 'EMA form'), ('Employee Induction form', 'Employee Induction form'), ('Evaluation', 'Evaluation'), ('Fire extinguishers inspection form', 'Fire extinguishers inspection form'), ('HIRA', 'HIRA'), ('Induction manual', 'Induction manual'), ('Inspection', 'Inspection'), ('Indemnity form', 'Indemnity form'), ('Near miss report form', 'Near miss report form'), ('Petty cash', 'Petty cash'), ('Planned Job Observation', 'Planned Job Observation'), ('PPE Card', 'PPE Card'), ('Release form', 'Release form'), ('Request form', 'Request form'), ('Stop and fix form', 'Stop and fix form'), ('Training Register', 'Training Register'), ('Tree cutting permit', 'Tree cutting permit'), ('Visitor Induction form', 'Visitor Induction form'), ('VFL', 'VFL')], max_length=250)),
                ('description', models.TextField(blank=True)),
                ('upload_file', models.FileField(upload_to='ims_06/blank_forms')),
                ('active', models.BooleanField(default=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
    ]
