# Generated by Django 3.2.7 on 2021-11-15 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IMS_06_Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('SHE', 'SHE'), ('HR', 'HR'), ('Finance', 'Finance'), ('Technical Services', 'Technical Services'), ('Reduction', 'Reduction'), ('Engineering', 'Engineering'), ('Security', 'Security'), ('Muriel Mine', 'Muriel Mine'), ('Other', 'Other')], max_length=250)),
                ('category', models.CharField(choices=[('Baseline Risk Assessment (BRA)', 'Baseline Risk Assessment (BRA)'), ('Issue Based Risk Assessment', 'Issue Based Risk Assessment'), ('Compliance Obligations Register', 'Compliance Obligations Register'), ('IMS Objectives and targets', 'IMS Objectives and targets'), ('ACTs', 'ACTs'), ('Blank forms', 'Blank forms')], max_length=250)),
                ('description', models.TextField(blank=True)),
                ('upload_file', models.FileField(upload_to='ims_06')),
                ('active', models.BooleanField(default=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
    ]
