# Generated by Django 3.2.7 on 2021-12-02 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessFlowChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('SHE', 'SHE'), ('HR', 'HR'), ('Finance', 'Finance'), ('Technical Services', 'Technical Services'), ('Reduction', 'Reduction'), ('Engineering', 'Engineering'), ('Security', 'Security')], max_length=250)),
                ('description', models.TextField(blank=True)),
                ('process_chart_file', models.FileField(upload_to='process_flow_chart')),
                ('active', models.BooleanField(default=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
        migrations.CreateModel(
            name='Organogram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('SHE', 'SHE'), ('HR', 'HR'), ('Finance', 'Finance'), ('Technical Services', 'Technical Services'), ('Reduction', 'Reduction'), ('Engineering', 'Engineering'), ('Security', 'Security')], max_length=250)),
                ('description', models.TextField(blank=True)),
                ('organogram_file', models.FileField(upload_to='organograms')),
                ('active', models.BooleanField(default=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
        migrations.CreateModel(
            name='NeedsAndExpetation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('SHE', 'SHE'), ('HR', 'HR'), ('Finance', 'Finance'), ('Technical Services', 'Technical Services'), ('Reduction', 'Reduction'), ('Engineering', 'Engineering'), ('Security', 'Security')], max_length=250)),
                ('description', models.TextField(blank=True)),
                ('needs_expetations_file', models.FileField(upload_to='needs_expetations')),
                ('active', models.BooleanField(default=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintsRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('SHE', 'SHE'), ('HR', 'HR'), ('Finance', 'Finance'), ('Technical Services', 'Technical Services'), ('Reduction', 'Reduction'), ('Engineering', 'Engineering'), ('Security', 'Security')], max_length=250)),
                ('description', models.TextField(blank=True)),
                ('complaints_register_file', models.FileField(upload_to='complaints_register')),
                ('active', models.BooleanField(default=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
    ]
