# Generated by Django 3.2.7 on 2021-09-25 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_04', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintsregister',
            name='complaints_register_file',
            field=models.FileField(upload_to='complaints_register'),
        ),
        migrations.AlterField(
            model_name='NeedsAndExpetation',
            name='needs_expetations_file',
            field=models.FileField(upload_to='needs_expetations'),
        ),
        migrations.AlterField(
            model_name='organogram',
            name='organogram_file',
            field=models.FileField(upload_to='organograms'),
        ),
        migrations.AlterField(
            model_name='processflowchart',
            name='process_chart_file',
            field=models.FileField(upload_to='process_flow_chart'),
        ),
    ]
