# Generated by Django 3.2.7 on 2021-11-21 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentNonConformityCorrectiveAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('SHE', 'SHE'), ('HR', 'HR'), ('Finance', 'Finance'), ('Technical Services', 'Technical Services'), ('Reduction', 'Reduction'), ('Engineering', 'Engineering'), ('Security', 'Security'), ('Other', 'Other')], max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('category', models.CharField(choices=[('Accident Investigation Reports', 'Accident Investigation Reports'), ('Near Miss Report', 'Near Miss Report'), ('Stop and Fix Reports', 'Stop and Fix Reports')], max_length=250)),
                ('description', models.TextField(blank=True)),
                ('upload_file', models.FileField(upload_to='ims10/all_reports')),
                ('active', models.BooleanField(default=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
    ]
