# Generated by Django 3.2.7 on 2021-12-02 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalPlanningControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('SHE', 'SHE'), ('HR', 'HR'), ('Finance', 'Finance'), ('Technical Services', 'Technical Services'), ('Reduction', 'Reduction'), ('Engineering', 'Engineering'), ('Security', 'Security'), ('Other', 'Other')], max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('category', models.CharField(choices=[('Standard Task Procedures', 'Standard Task Procedures'), ('Inspections', 'Inspections'), ('PJO and VFL', 'PJO and VFL')], max_length=250)),
                ('description', models.TextField(blank=True)),
                ('upload_file', models.FileField(upload_to='ims08/operational_planning_control')),
                ('active', models.BooleanField(default=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
        migrations.CreateModel(
            name='ManagementDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('category', models.CharField(choices=[('Management of Change', 'Management of Change'), ('Contractor Management', 'Contractor Management'), ('Emergency preparedness and response', 'Emergency preparedness and response'), ('Mock Drill Schedules, Reports and Action Plans', 'Mock Drill Schedules, Reports and Action Plans'), ('Register of emergency equipment ', 'Register of emergency equipment '), ('Audits, Inspections of emergency equipment', 'Audits, Inspections of emergency equipment'), ('Other', 'Other')], max_length=250)),
                ('description', models.TextField(blank=True)),
                ('upload_file', models.FileField(upload_to='ims08/management_documents')),
                ('active', models.BooleanField(default=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
    ]
